language: scala
scala:
  - 2.11.4
  - 2.10.4
jdk:
  - oraclejdk8
  - oraclejdk7
script: sbt ++$TRAVIS_SCALA_VERSION compile test package
matrix:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk7
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/de5b80b12c940df3782b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false
